version: '3.0'

services:
  url-phising:
    build: .
    command: python3 app.py
    volumes:
      - .:/app
      - /home/cnm9/HoangTrongBinh/ATTT_Project/modelDir:/app/modelDir
      - /home/cnm9/HoangTrongBinh/ATTT_Project/datasetDir:/app/datasetDir
    ports:
      - 5678:5678
